import "./globals.css";

import { Manrope } from "next/font/google";

const manrope = Manrope({
  subsets: ["latin"], // choose character sets
  variable: "--font-manrope", // optional CSS variable
  weight: ["400", "500", "600", "700"], // pick the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Bootstrap CSS */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity=""
          crossOrigin="anonymous"
        />
        <link rel="stylesheet" href="bower_components/aos/dist/aos.css" />
      </head>
      <body className={`${manrope.variable}`}>
        {children}
        {/* Bootstrap JS */}
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
        <script src="bower_components/aos/dist/aos.js"></script>
      </body>
    </html>
  );
}
